version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: powerki_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: joelito
      MYSQL_DATABASE: shopdb
      MYSQL_USER: powerki_user
      MYSQL_PASSWORD: powerki_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - powerki_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Backend
  backend:
    build:
      context: ./back_end/server
      dockerfile: Dockerfile
    container_name: powerki_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shopdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: joelito
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - powerki_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # React Frontend
  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    container_name: powerki_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - powerki_network

volumes:
  mysql_data:
    driver: local

networks:
  powerki_network:
    driver: bridge 